import type { Metadata } from "next";
import ClientLayout from "./client-layout";
import GeminiCuisineChatbot from "@/components/main/recommendations/gemini-cuisine-chatbot";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "ReFresh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <ClientLayout>
        {children}
        <GeminiCuisineChatbot /> {/* Add the chatbot to the layout */}
      </ClientLayout>
    </SessionProvider>
  );
}
